version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: exam
    ports:
      - "9308:3306"  # MySQL service mapped to port 9308
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot@123"]
      interval: 30s
      timeout: 10s
      retries: 5

  examninja-backend:
    image: ${ECR_REGISTRY}/examninja:backend_latest
    container_name: examninja-backend-container
    ports:
      - "8085:8080"  # Backend service mapped to port 8085
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  examninja-frontend:
    image: ${ECR_REGISTRY}/examninja:frontend_latest
    container_name: examninja-frontend-container
    ports:
      - "3000:3000"  # Frontend service mapped to port 3001
    depends_on:
      examninja-backend:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
